server:
  port: 8080

#H2
spring:
  h2:
    console:
      path: /h2-console
      enabled: true
#DataSource
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:stock
      driver-class-name: org.h2.Driver
      username: sa
      password:

  #jpa
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    enabled: true
    path: /docs-api
  api-docs:
    path: /api-docs

